# Generated by Django 5.2.4 on 2025-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_management', '0002_emprestimo_equipamento_alter_colaborador_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_emprestimos', models.PositiveIntegerField(default=0)),
                ('total_devolvidos', models.PositiveIntegerField(default=0)),
                ('total_pendentes', models.PositiveIntegerField(default=0)),
                ('ultimo_emprestimo', models.DateField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epi_management.colaborador')),
                ('equipamento_mais_frequente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epi_management.equipamento')),
            ],
            options={
                'verbose_name': 'Relatório de Empréstimo',
                'verbose_name_plural': 'Relatórios de Empréstimos',
            },
        ),
    ]
